### ISSUE TITLE
Can't work properly deployed to an envoy gateway

### ISSUE THREAD

**Issue by SoaringPhoenix** [halfrost/sentinel-go-envoy-proxy-wasm#2]
Dear halfrost, sorry to bother.

I tried to install your wasm binary to my envoy gateway, but encountered some problem.
My envoyFilter looks like the following

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: sentinal-extension
  namespace: xxx
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.tcp_proxy
    patch:
      operation: INSERT_FIRST
      value:
        name: envoy.filters.network.wasm
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {"config_path": "/etc/sentinel.yaml","resource_name": "hello"}
              vm_config:
                code:
                  local:
                    filename: /etc/main.wasm
                configuration:
                  '@type': type.googleapis.com/google.protobuf.StringValue
                  value: |
                    {"config_path": "/etc/sentinel.yaml","resource_name": "hello"}
                runtime: envoy.wasm.runtime.v8
                vm_id: headers-extension-vm
  workloadSelector:
    labels:
      aaa: bbb
      ccc:ddd
```

I used the main.wasm binary you uploaded in the ealier versions of this repo.

My sentinel.yaml is basically the same as yours in the repo, and I put it in the pod of my envoy gateway.

My envoy version is 
5952f5fb5f85f495ac6d0925539dcd445cd618a0/1.18.3/Clean/RELEASE/BoringSSL

when I tried to send some load to my envoy gateway, it receives the following:
![image](https://user-images.githubusercontent.com/34622167/201290889-f42618c9-109b-4018-a886-c1d081769000.png)

looks like the contextId failed to create caused the panic.

Anyway, I'm wondering if you could help me with it and see where i went wrong.
Many thanks in advance!

@halfrost
